target:
  name: bbu
  train_jsonl: data/bbu_full_768_poly/train_tiny.jsonl
  val_jsonl: data/bbu_full_768_poly/val_tiny.jsonl
  template: bbu_dense

sources:
  - name: lvis
    train_jsonl: public_data/lvis/rescale_32_768_poly_max_12/train_tiny.jsonl
    ratio: 0.08
    template: aux_dense
    max_objects_per_image: 5
