target:
  name: bbu
  train_jsonl: data/bbu_full_768_poly/train.jsonl
  val_jsonl: data/bbu_full_768_poly/val.jsonl
  template: bbu_dense
  
sources:
  - name: lvis
    train_jsonl: public_data/lvis/rescale_32_768_poly_max_12/train.jsonl
    ratio: 0.08
    template: aux_dense
    max_objects_per_image: 5
