extends: ../base/summary.yaml

targets:
  - name: bbu_summary
    train_jsonl:
    val_jsonl:
  - name: rru_summary
    train_jsonl:
    val_jsonl:

sources:
  - name: bbu_dense
    train_jsonl:
  - name: rru_dense
    train_jsonl:
