training:
  # Summary SFT overrides.
  output_dir: null
  logging_dir: null
  run_name: null
  num_train_epochs: null
  learning_rate: null
  vit_lr: null
  aligner_lr: null
  save_delay_steps: 300
  warmup_ratio: 0.05
