extends: summary_grpo_base.yaml

training:
  run_name: temperature_0.7-num_generations_4-eff_bs_32-gen_bs_32-vllm_server

rlhf:
  vllm_mode: server
  vllm_server_host: ["127.0.0.1"]
  vllm_server_port: [8000]
  vllm_server_timeout: 240
  vllm_tensor_parallel_size: 2
  vllm_data_parallel_size: 1
