extends:
  - dense_base.yaml

model:
  model: model_cache/models/Qwen/Qwen3-VL-4B-Instruct

training:
  output_dir: ./output/12-27/new_schema-4B-dense
  run_name: epoch_30-2_1_6
  num_train_epochs: 30
  learning_rate: 2.0e-4
  vit_lr: 1.0e-4
  aligner_lr: 6.0e-4
  logging_dir: ./tb/12-27/new_schema-4B

custom:
  fusion_config: configs/fusion/variants/bbu_rru_dense_1024.yaml
  use_summary: false
