extends:
  - ../../base.yaml
  - ../../components/global/max_length_12000.yaml
  - ../../components/tuner/dora_full.yaml
  - ../../components/training/sft_defaults.yaml
  - ../../components/data/loader_defaults.yaml
  - ../../components/prompts/summary_runtime_bbu.yaml
  - ../../components/custom/common_fusion.yaml
  - ../../components/custom/assistant_prefix.yaml
  - ../../components/custom/augmentation_dense.yaml
  - ../../components/deepspeed/zero2.yaml

model:
  # Explicitly required in launch configs.
  model: null
