extends:
  - ../../base.yaml
  - ../../components/global/max_length_16000.yaml
  - ../../components/tuner/dora_full.yaml
  - ../../components/tuner/summary_freeze.yaml
  - ../../components/training/sft_defaults.yaml
  - ../../components/training/summary_sft.yaml
  - ../../components/data/loader_defaults.yaml
  - ../../components/prompts/summary_runtime_bbu.yaml
  - ../../components/custom/common_fusion.yaml
  - ../../components/custom/assistant_prefix.yaml
  - ../../components/custom/summary_mode.yaml
  - ../../components/custom/augmentation_summary.yaml
  - ../../components/deepspeed/zero2.yaml

model:
  model: null
