extends: ./sft_base.yaml

prompts:
  profile: summary_runtime
  domain: bbu

custom:
  fusion_config: configs/dataset_mix/bbu_rru_dense_new_schema_1024.yaml
  use_summary: false
  assistant_prefix_format: "<DOMAIN={domain}>, <TASK={task}>"
