extends:
  - summary_2048.yaml

model:
  model: output/1-4/2048_res_dense_merged/epoch_4-ckpt-5960

training:
  output_dir: ./output/1-6/grpo_summary_2048
  run_name: temperature_0.7-num_generations_4-eff_bs_32-gen_bs_32-vllm_server
  logging_dir: ./tb/1-6/grpo_summary_2048
  num_train_epochs: 2
  learning_rate: 1.0e-5
  vit_lr: 1.0e-7
  aligner_lr: 1.0e-7

rlhf:
  vllm_mode: server
  vllm_server_host: ["127.0.0.1"]
  vllm_server_port: [8000]
  vllm_server_timeout: 240
  vllm_tensor_parallel_size: 2
  vllm_data_parallel_size: 1
